#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "hybrid"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # script in ~/.SpaceVim.d/autoload
    bootstrap_before = "myspacevim#before"
    # default indent
    default_indent = 4
    ignorecase = true
    smartcase = true

# Enable autocomplete layer
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "cycle"

[[layers]]
    name = "shell"
    default_position = "bottom"
    default_height = 30

[[layers]]
    name = "core"
    enable_smooth_scrolling = false

[[layers]]
    name = "tmux"

[[layers]]
    name = "fzf"

[[layers]]
    name = "git"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "sudo"

[[layers]]
    name = "lang#go"
    format_on_save = true

[[layers]]
    name = "lang#c"
    clang_executable = "/usr/bin/clang"
    enable_clang_syntax_highlight = true
    clang_flag = ['-I/usr/include', '-I/usr/local/include', '-Wall', '-Werror']
    [layer.clang_std]
        c = "c17"
        cpp = "c++20"

[[layers]]
    name = "lsp"
    filetypes = [
      "c",
      "cpp"
    ]
    enable = false

[[layers]]
    name = "format"

